// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var m=this,aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){ea=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
ba:da;return ea.apply(null,arguments)},fa=null;Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return ea.apply(null,c)}return ea(this,a)};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ga=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,ha=function(a){if(null==a)return String(a);var b=ga.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},ia=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},ka=function(a){if(!a||"object"!=ha(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!ia(a,"constructor")&&!ia(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||ia(a,c)},la=function(a,b){var c=b||("array"==ha(a)?[]:{}),d;for(d in a)if(ia(a,d)){var e=a[d];"array"==ha(e)?("array"!=ha(c[d])&&(c[d]=[]),c[d]=la(e,c[d])):ka(e)?(ka(c[d])||(c[d]={}),c[d]=la(e,c[d])):c[d]=e}return c};var ma=function(){},w=function(a){return"function"==typeof a},x=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},na=function(a){return"number"==ha(a)&&!isNaN(a)},oa=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},pa=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},C=function(a){return Math.round(Number(a))||0},qa=function(a){var b=[];if(x(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));
return b},E=function(){return new Date},ra=function(a,b){if(!na(a)||!na(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},sa=function(){this.prefix="gtm.";this.ra={}};sa.prototype.set=function(a,b){this.ra[this.prefix+a]=b};sa.prototype.get=function(a){return this.ra[this.prefix+a]};sa.prototype.contains=function(a){return void 0!==this.get(a)};
var ta=function(a,b,c){try{return a["1"](a,b||ma,c||ma)}catch(d){}return!1},va=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=pa(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},wa=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},xa=function(a){for(var b=0;b<a.length;b++)a[b]()},ya=E().getTime(),za=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Aa=function(a,
b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c};var F=window,I=document,Ba=navigator,K=function(a,b,c){var d=F[a],e="var "+a+";";if(m.execScript)m.execScript(e,"JavaScript");else if(m.eval)if(null==fa&&(m.eval("var _et_ = 1;"),"undefined"!=typeof m._et_?(delete m._et_,fa=!0):fa=!1),fa)m.eval(e);else{var f=m.document,g=f.createElement("script");g.type="text/javascript";g.defer=!1;g.appendChild(f.createTextNode(e));f.body.appendChild(g);f.body.removeChild(g)}else throw Error("goog.globalEval not available");F[a]=void 0===d||c?b:d;return F[a]},L=
function(a,b,c,d){return(d||"http:"!=F.location.protocol?a:b)+c},Ca=function(a){var b=I.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},Da=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},M=function(a,b,c){var d=I.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;Da(d,b);c&&(d.onerror=c);Ca(d)},Ea=function(a,b){var c=I.createElement("iframe");c.height="0";c.width=
"0";c.style.display="none";c.style.visibility="hidden";Ca(c);Da(c,b);void 0!==a&&(c.src=a);return c},k=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},N=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},O=function(a){F.setTimeout(a,0)},Ha=!1,Ia=[],Ja=function(a){if(!Ha){var b=I.createEventObject,c="complete"==I.readyState,d="interactive"==I.readyState;if(!a||"readystatechange"!=
a.type||c||!b&&d){Ha=!0;for(var e=0;e<Ia.length;e++)Ia[e]()}}},La=0,Ma=function(){if(!Ha&&140>La){La++;try{I.documentElement.doScroll("left"),Ja()}catch(a){F.setTimeout(Ma,50)}}},Na=function(a){var b=I.getElementById(a);if(b&&R(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(R(document.all[a][c],"id")==a)return document.all[a][c];return b},R=function(a,b){return a&&b&&a.attributes[b]?a.attributes[b].value:null},Oa=function(a){return a.target||a.srcElement||{}},Pa=function(a,b){for(var c={},
d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Qa=!1,Ra=[],Sa=function(){if(!Qa){Qa=!0;for(var a=0;a<Ra.length;a++)Ra[a]()}},Ta=function(a){a=a||F;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)};var Ua=null,Va=null;var Wa=new sa,Xa={},Ya=ma,Za=[],$a=!1,cb={set:function(a,b){la(ab(a,b),Xa)},get:function(a){return S(a,2)}},db=function(a){var b=!1;return function(){!b&&w(a)&&O(a);b=!0}},nb=function(){for(var a=!1;!$a&&0<Za.length;){$a=!0;var b=Za.shift();if(w(b))try{b.call(cb)}catch(c){}else if(x(b))e:{var d=b;if("string"==ha(d[0])){for(var e=d[0].split("."),f=e.pop(),g=d.slice(1),h=Xa,n=0;n<e.length;n++){if(void 0===h[e[n]])break e;h=h[e[n]]}try{h[f].apply(h,g)}catch(q){}}}else{var l=b,p=void 0;for(p in l)if(l.hasOwnProperty(p)){var r=
p,s=l[p];Wa.set(r,s);la(ab(r,s),Xa)}var H=!1,J=l.event;if(J){Va=J;var v=db(l.eventCallback),U=l.eventTimeout;U&&F.setTimeout(v,Number(U));H=Ya(J,v)}if(!Ua&&(Ua=l["gtm.start"])){}Va=null;a=H||a}var P=b,Q=Xa;mb();$a=!1}return!a},S=function(a,b){if(2==b){for(var c=Xa,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Wa.get(a)},ab=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var ob={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},pb={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],
nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},qb=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},fb=function(){var a=S("gtm.whitelist"),b=a&&qb(qa(a),ob),c=S("gtm.blacklist")||S("tagTypeBlacklist"),d=c&&qb(qa(c),pb),e={};return function(f){var g=f&&f["1"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)e:{if(0>oa(b,g.a))if(g.b&&0<g.b.length)for(var n=0;n<g.b.length;n++){if(0>
oa(b,g.b[n])){h=!1;break e}}else{h=!1;break e}h=!0}var q=!1;if(c){var l;if(!(l=0<=oa(d,g.a)))e:{for(var p=g.b||[],r=new sa,s=0;s<d.length;s++)r.set(d[s],!0);for(s=0;s<p.length;s++)if(r.get(p[s])){l=!0;break e}l=!1}q=l}return e[g.a]=!h||q}};var rb=function(a,b,c,d,e){var f=a.hash?a.href.replace(a.hash,""):a.href,g=(a.protocol.replace(":","")||F.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||F.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:F.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":var f="/"==a.pathname.substr(0,1)?a.pathname:"/"+
a.pathname,n=f.split("/");0<=oa(d||[],n[n.length-1])&&(n[n.length-1]="");f=n.join("/");break;case "query":f=a.search.replace("?","");if(e)e:{for(var q=f.split("&"),l=0;l<q.length;l++){var p=q[l].split("=");if(decodeURIComponent(p[0]).replace("+"," ")==e){f=decodeURIComponent(p.slice(1).join("=")).replace("+"," ");break e}}f=void 0}break;case "fragment":f=a.hash.replace("#","")}return f},sb=function(a){var b=I.createElement("a");b.href=a;return b};var _eu=function(a){var b=String(S("gtm.elementUrl")||a[""]||""),c=sb(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Va};_e.a="e";_e.b=["google"];var _v=function(a){var b=S(a["3"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(S("gtm.referrer")||I.referrer),c=sb(b);return b};_f.a="f";_f.b=["google"];var tb=function(a){var b=F.location,c=b.hash?b.href.replace(b.hash,""):b.href,d;if(d=a[""]?a[""]:S("gtm.url"))c=String(d),b=sb(c);var e,f,g;
a["0"]&&(c=rb(b,a["0"],e,f,g));return c},_u=tb;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[""])==String(a[""])};_eq.a="eq";_eq.b=["google"];var yb=/(Firefox\D28\D)/g.test(Ba.userAgent),Bb=function(a,b,c,d){return function(e){e=e||F.event;var f=Oa(e),g=!1;if(3!==e.which||"CLICK"!=a&&"LINK_CLICK"!=a)if(2!==e.which&&(null!=e.which||4!=e.button)||"LINK_CLICK"!=a)if("LINK_CLICK"==a&&(f=Pa(f,["a","area"]),g=!f||!f.href||e.ctrlKey||e.shiftKey||e.altKey||!0===e.metaKey),e.defaultPrevented||!1===e.returnValue||e.R&&e.R()){if(!c&&f){var h={simulateDefault:!1};zb(a,f,h,d)}}else{if(f){var h={},n=zb(a,f,h,d),g=g||n||"LINK_CLICK"==a&&yb;h.simulateDefault=
!n&&b&&!g;h.simulateDefault&&(g=Ab(f,h)||g,!g&&e.preventDefault&&e.preventDefault());e.returnValue=n||!b||g;return e.returnValue}return!0}}},zb=function(a,b,c,d){var e=d||2E3,f={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||R(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":f.event="gtm.linkClick";f["gtm.elementUrl"]=b.href;f.eventTimeout=e;f.eventCallback=Cb(b,c);break;case "FORM_SUBMIT":f.event="gtm.formSubmit";var g=b.action;g&&
g.tagName&&(g=b.cloneNode(!1).action);f["gtm.elementUrl"]=g;f.eventTimeout=e;f.eventCallback=Db(b,c);break;case "CLICK":f.event="gtm.click";f["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return F["dataLayer"].push(f)},Eb=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},Ab=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(Ba.userAgent),e=Eb(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;
f=(e||"_self").substring(1);b.targetWindow=F.frames&&F.frames[f]||F[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+E().getTime(),b.targetWindow=F.open("",b.targetWindowName));break;default:d&&!F.frames[e]?(b.simulateDefault=!1,c=!0):(F.frames[e]||(b.targetWindowName=e),b.targetWindow=F.frames[e]||F.open("",e))}return c},Cb=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||E().getTime(),500>E().getTime()-
c&&F.setTimeout(Cb(a,b,c),25)))}},Db=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);I.gtmSubmitFormNow=!0;Fb(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||E().getTime(),500>E().getTime()-c&&F.setTimeout(Db(a,b,c),25)}},Gb=function(a,b,c,d){var e,f;switch(a){case "CLICK":if(I.gtmHasClickListenerTag)return;I.gtmHasClickListenerTag=!0;e="click";f=function(a){var b=Oa(a);b&&zb("CLICK",b,{},d);return!0};
break;case "LINK_CLICK":if(I.gtmHasLinkClickListenerTag)return;I.gtmHasLinkClickListenerTag=!0;e="click";f=Bb(a,b||!1,c||!1,d);break;case "FORM_SUBMIT":if(I.gtmHasFormSubmitListenerTag)return;I.gtmHasFormSubmitListenerTag=!0;e="submit";f=Bb(a,b||!1,c||!1,d);break;default:return}N(I,e,f,!1)},Fb=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;I.gtmFormElementSubmitter||(I.gtmFormElementSubmitter=
I.createElement("form"));return I.gtmFormElementSubmitter.submit.call?I.gtmFormElementSubmitter.submit:a.submit};var Hb=function(a,b){return a<b?-1:a>b?1:0};var Kb;e:{var Lb=m.navigator;if(Lb){var Mb=Lb.userAgent;if(Mb){Kb=Mb;break e}}Kb=""}var Nb=function(a){return-1!=Kb.indexOf(a)};var Ob=Nb("Opera")||Nb("OPR"),X=Nb("Trident")||Nb("MSIE"),Pb=Nb("Gecko")&&-1==Kb.toLowerCase().indexOf("webkit")&&!(Nb("Trident")||Nb("MSIE")),Qb=-1!=Kb.toLowerCase().indexOf("webkit"),Rb=function(){var a=m.document;return a?a.documentMode:void 0},Sb=function(){var a="",b;if(Ob&&m.opera){var c=m.opera.version;return"function"==aa(c)?c():c}Pb?b=/rv\:([^\);]+)(\)|;)/:X?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Qb&&(b=/WebKit\/(\S+)/);if(b)var d=b.exec(Kb),a=d?d[1]:"";if(X){var e=Rb();if(e>parseFloat(a))return String(e)}return a}(),
Ub={},Vb=function(a){var b;if(!(b=Ub[a])){for(var c=0,d=String(Sb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",n=e[g]||"",q=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var p=q.exec(h)||["","",""],r=l.exec(n)||["","",""];if(0==p[0].length&&0==r[0].length)break;c=Hb(0==p[1].length?0:parseInt(p[1],10),0==r[1].length?0:parseInt(r[1],10))||Hb(0==p[2].length,0==
r[2].length)||Hb(p[2],r[2])}while(0==c)}b=Ub[a]=0<=c}return b},Wb=m.document,Xb=Wb&&X?Rb()||("CSS1Compat"==Wb.compatMode?parseInt(Sb,10):5):void 0;var Yb;if(!(Yb=!Pb&&!X)){var Zb;if(Zb=X)Zb=X&&9<=Xb;Yb=Zb}Yb||Pb&&Vb("1.9.1");X&&Vb("9");var $b=function(a){$b[" "](a);return a};$b[" "]=function(){};var ec=function(a,b){var c="";X&&!ac(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(bc)a.srcdoc=d;else if(cc){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else dc(a,d)},bc=Qb&&"srcdoc"in document.createElement("iframe"),cc=Pb||Qb||X&&Vb(11),dc=function(a,b){X&&Vb(7)&&!Vb(10)&&6>fc()&&gc(b)&&(b=hc(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};X&&!ac(a)?ic(a,c):c()},fc=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},ac=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)t:{try{$b(c.foo);d=!0;break t}catch(e){}d=!1}b=d}catch(f){b=!1}return b}catch(g){return!1}},jc=0,ic=function(a,b){var c="goog_rendering_callback"+jc++;window[c]=b;X&&Vb(6)&&!Vb(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},gc=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},hc=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),
d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var sc,tc;
var Dc=function(a){return function(){}},Ec=function(a){return function(){}};var Qc=function(a){var b=F||m,c=b.onerror,d=!1;Qb&&!Vb("535.3")&&(d=!d);b.onerror=function(b,f,g,h,n){c&&c(b,f,g,h,n);a({message:b,fileName:f,Wa:g,pb:h,error:n});return d}};var nd=function(){this.f=[]};nd.prototype.set=function(a,b){this.f.push([a,b]);return this};nd.prototype.resolve=function(a,b){for(var c={},d=0;d<this.f.length;d++){var e=od(this.f[d][0],a,b),f=od(this.f[d][1],a,b);c[e]=f}return c};var pd=function(a){this.index=a};pd.prototype.resolve=function(a,b){var c=gb[this.index];if(c&&!b(c)){var d=c["2"];if(a){if(a.get(d))return;a.set(d,!0)}c=od(c,a,b);a&&a.set(d,!1);return ta(c)}};
for(var _M=function(a){return new pd(a)},rd=function(a){this.resolve=function(b,c){for(var d=[],e=0;e<a.length;e++)d.push(od(qd[a[e]],b,c));return d.join("")}},_T=function(a){return new rd(arguments)},sd=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=function(c,d){if(a[0]instanceof pd&&b(8)&&b(16))return'google_tag_manager["GTM-MRX4JH"].macro('+a[0].index+")";for(var e=String(od(a[0],c,d)),f=1;f<a.length;f++)e=Z[a[f]](e);return e}},_E=function(a,b){return new sd(arguments)},lb=function(a,b){return od(a,new sa,b)},od=function(a,b,c){var d=a;if(a instanceof pd||a instanceof nd||a instanceof rd||
a instanceof sd)return a.resolve(b,c);if(x(a))for(var d=[],e=0;e<a.length;e++)d[e]=od(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=od(a[f],b,c))}return d},td=function(a,b){var c=b[a],d=c;if(c instanceof pd||c instanceof sd||c instanceof rd)d=c;else if(x(c))for(var d=[],e=0;e<c.length;e++)d[e]=td(c[e],b);else if("object"==typeof c){var d=new nd,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],td(c[f],b))}return d},wd=function(a,b){for(var c=b?b.split(","):[],
d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=qd[e[1]]);if(1==a)for(var f=ud(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=vd[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=ud(e[g])}return c},ud=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<xd;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},
xd=21,yd=[_v,'element url','gtm.elementUrl','element target','gtm.elementTarget','element id','gtm.elementId','element classes','gtm.elementClasses','element','gtm.element',_e,'event',_f,'referrer',_u,'url path','path','url hostname','host','url'],zd=[],Ad=0;Ad<yd.length;Ad++)zd[Ad]=td(Ad,yd);var qd=zd,vd=wd(0,"1:0,2:1,3:2,2:3,3:4,2:5,3:6,2:7,3:8,2:9,3:10,1:11,2:12,1:13,2:14,1:15,2:16,0:17,2:18,0:19,2:20"),gb=wd(1,"H,Z,hB,BG,BY,AgB,AAG,AA4,AAID,AAIE"),Bd=wd(1,""),$=wd(1,""),Cd=wd(2,"");
var mb=function(){};var Pd=function(){var a=this;this.v=!1;this.B=[];this.M=[];this.la=function(){a.v||xa(a.B);a.v=!0};this.ka=function(){a.v||xa(a.M);a.v=!0};this.N=ma},Qd=function(){this.k=[];this.aa={};this.O=[];this.r=0};Qd.prototype.addListener=function(a){this.O.push(a)};var Rd=function(a,b,c,d){if(!c.v){a.k[b]=c;void 0!==d&&(a.aa[b]=d);a.r++;var e=function(){0<a.r&&a.r--;0<a.r||xa(a.O)};c.B.push(e);c.M.push(e)}};var Sd=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Bd[b]&&lb(Bd[b],c);a[b]=[d&&ta(d),d]}return a[b]}},Td=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.d(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.d(e[d],a.c)[0])return!1;return!0},Ud=function(a,b){return function(){a["4"]=b.la;a["5"]=b.ka;ta(a,b.la,b.ka)}},Ya=function(a,b){S("tagTypeBlacklist");for(var c={name:a,Ia:b||ma,s:ud(),t:ud(),d:Sd(),c:fb()},d=0;d<Cd.length;d++)if(Td(c,
Cd[d])){for(var e=c,f=Cd[d],g=f[1],h=0;h<g.length;h++)e.s[g[h]]=!0;for(var n=f[3],h=0;h<n.length;h++)e.t[n[h]]=!0}var q=[];for(var l=0;l<xd;l++)if(c.s[l]&&!c.t[l])if(c.c($[l])){}else{q[l]=lb($[l],c.c);}c.C=q;for(var p=
new Qd,r=0;r<xd;r++)if(c.s[r]&&!c.t[r]&&!c.c($[r])){var s=c.C[r],H=new Pd;H.B.push(Dc(s));H.M.push(Ec(s));H.N=Ud(s,H);Rd(p,r,H,s[""])}p.addListener(c.Ia);for(var J=[],v=0;v<p.k.length;v++){var U=p.k[v];if(U){var A=p.aa[v];void 0!==A?A!=v&&p.k[A]&&p.k[A].B.push(U.N):J.push(v)}}for(v=0;v<J.length;v++)p.k[J[v]].N();0<p.r||xa(p.O);return 0<c.C.length};var Vd={macro:function(a){return gb[a]&&lb(_M(a),fb())}};Vd.dataLayer=cb;Vd.Xa=function(){var a=F.google_tag_manager;a||(a=F.google_tag_manager={});a["GTM-MRX4JH"]||(a["GTM-MRX4JH"]=Vd)};Vd.Xa();
(function(){var a=K("dataLayer",[],!1),b=K("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};Ia.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Ra.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Za.push.apply(Za,b);300<this.length;)this.shift();return nb()};Za.push.apply(Za,a.slice(0));O(nb)})();
if("interactive"==I.readyState&&!I.createEventObject||"complete"==I.readyState)Ja();else{N(I,"DOMContentLoaded",Ja);N(I,"readystatechange",Ja);if(I.createEventObject&&I.documentElement.doScroll){var Wd=!0;try{Wd=!F.frameElement}catch(Yd){}Wd&&Ma()}N(F,"load",Ja)}"complete"===I.readyState?Sa():N(F,"load",Sa);var _vs="res_ts:1381763065245000,srv_cl:70073416,ds:live,cv:1";
})()
